station_amenities_objects= {
    "NSG-1": {
        "Minimum Essential Amenities": {
            "Drinking water": "20 taps/PF",
            "Waiting hall": "250 sqm",
            "Platform shelter": "500 sqm",
            "Urinals": "12",
            "Lighting": "As per norms",
            "Dustbins": "Yes",
            "Clock": "To be decided by zonal railways",
            "Time Table Display": "As per instructions",
            "Public Address System": "Yes",
            "Parking-circulatory area with lights": "As per instructions",
            "Electronic Train indicator board": "As per instructions",
            "Signage": "Yes",
            "Seating arrangement": "150 seats/PF",
            "Latrines": "12",
            "Foot over bridge": "1 with cover",
            "Water cooler": "2 on each PF"
        },
        "Recommended": {
            "Clock": "To be decided by the Zonal Railways",
            "Bathrooms": "1/400 Ndb",
            "Water Coolers": "To be provided if the total number of passengers, inward and outward, exceeds 1000 per day",
            "IVRS": "48 lines (calls 72000)",
            "Public Address System": "To be decided by the Zonal Railways",
            "Parking-circulatory Area": "To be decided by the Zonal Railways",
            "Electronic Train Indicator Board": "To be decided by the Zonal Railways",
            "Public Phone Booth": "To be decided by the Zonal Railways",
            "Signage": "To be decided by the Zonal Railways",
            "Coach Guidance System": "Available",
            "Insect Catchers": "Available",
            "Infant Nursing Cubicle": "Available",
            "Universal Mobile Charging Points": "To be decided by the Zonal Railways",
            "Emergency Lighting": "10 light points per platform, backup from DG set/Solar"
        },
        "Desirable": {
            "Food Courts": "Yes",
            "Prepaid Taxi Service": "Yes",
            "Wheelchair Accessibility": "Yes",
            "Retiring Room": "Yes",
            "Waiting room with bathing facilities": "Yes",
            "Separate waiting for ladies": "Yes",
            "Enquiry System": "Yes",
            "Food Plaza": "Yes",
            "Automatic Vending Machines": "Yes",
            "Coin-operated Ticket Vending Machines": "Yes",
            "Second entry with booking office": "Yes",
            "Washable apron with direct watering facilities": "Yes",
            "Access control": "Yes"
        }
    },
    "NSG-2": {
        "Minimum Essential Amenities": {
            "Drinking water": "20 taps/PF",
            "Waiting hall": "250 sqm",
            "Platform shelter": "500 sqm",
            "Urinals": "12",
            "Lighting": "As per norms",
            "Dustbins": "Yes",
            "Clock": "To be decided by zonal railways",
            "Time Table Display": "As per instructions",
            "Public Address System": "Yes",
            "Parking-circulatory area with lights": "As per instructions",
            "Electronic Train indicator board": "As per instructions",
            "Signage": "Yes",
            "Seating arrangement": "150 seats/PF",
            "Latrines": "12",
            "Foot over bridge": "1 with cover",
            "Water cooler": "2 on each PF"
        },
        "Recommended": {
 "Clock": "To be decided by the Zonal Railways",
        "Bathrooms": "1/400 Ndb",
        "Water Coolers": "To be provided if total passengers exceed 1000 per day",
        "IVRS": "48 lines (calls 72000)",
        "Public Address System": "To be decided by the Zonal Railways",
        "Parking-circulatory Area": "To be decided by the Zonal Railways",
        "Electronic Train Indicator Board": "To be decided by the Zonal Railways",
        "Public Phone Booth": "To be decided by the Zonal Railways",
        "Signage": "To be decided by the Zonal Railways",
        "Coach Guidance System": "Available",
        "Insect Catchers": "Available",
        "Infant Nursing Cubicle": "Available",
        "Universal Mobile Charging Points": "To be decided by the Zonal Railways",
        "Emergency Lighting": "Backup source from DG set/Solar"
        },
        "Desirable": {
            "Food Courts": "Yes",
            "Prepaid Taxi Service": "Yes",
            "Wheelchair Accessibility": "Yes",
            "Retiring Room": "Yes",
            "Waiting room with bathing facilities": "Yes",
            "Separate waiting for ladies": "Yes",
            "Enquiry System": "Yes",
            "Food Plaza": "Yes",
            "Automatic Vending Machines": "Yes",
            "Coin-operated Ticket Vending Machines": "Yes",
            "Second entry with booking office": "Yes",
            "Washable apron with direct watering facilities": "Yes"
        }
    },
    "NSG-3": {
        "Minimum Essential Amenities": {
            "Drinking water": "20 taps/PF",
            "Waiting hall": "125 sqm",
            "Platform shelter": "400 sqm",
            "Urinals": "10",
            "Lighting": "As per norms",
            "Dustbins": "Yes",
            "Clock": "To be decided by zonal railways",
            "Time Table Display": "As per instructions",
            "Public Address System": "Yes",
            "Parking-circulatory area with lights": "As per instructions",
            "Electronic Train indicator board": "As per instructions",
            "Signage": "Yes",
            "Seating arrangement": "125 seats/PF",
            "Latrines": "10",
            "Foot over bridge": "1 with cover",
            "Water cooler": "2 on each PF"
        },
        "Recommended": {
        "Clock": "To be decided by the Zonal Railways",
        "Bathrooms": "1/400 Ndb",
        "Water Coolers": "To be provided if total passengers exceed 1000 per day",
        "IVRS": "24 lines (calls 5000-20000)",
        "Public Address System": "To be decided by the Zonal Railways",
        "Parking-circulatory Area": "To be decided by the Zonal Railways",
        "Electronic Train Indicator Board": "To be decided by the Zonal Railways",
        "Public Phone Booth": "To be decided by the Zonal Railways",
        "Signage": "To be decided by the Zonal Railways",
        "Coach Guidance System": "Available",
        "Insect Catchers": "Available",
        "Infant Nursing Cubicle": "Available",
        "Universal Mobile Charging Points": "To be decided by the Zonal Railways",
        "Emergency Lighting": "Backup source from DG set/Solar"
        },
        "Desirable": {
            "Food Courts": "Yes",
            "Prepaid Taxi Service": "Yes",
            "Wheelchair Accessibility": "Yes",
            "Retiring Room": "Yes",
            "Waiting room with bathing facilities": "Yes",
            "Separate waiting for ladies": "Yes",
            "Enquiry System": "Yes",
            "Food Plaza": "Yes",
            "Automatic Vending Machines": "Yes",
            "Coin-operated Ticket Vending Machines": "Yes",
            "Modular Catering Stalls": "Yes"
        }
    },
    "NSG-4": {
        "Minimum Essential Amenities": {
            "Drinking water": "20 taps/PF",
            "Waiting hall": "75 sqm",
            "Platform shelter": "200 sqm",
            "Urinals": "6",
            "Lighting": "As per norms",
            "Dustbins": "Yes",
            "Clock": "To be decided by zonal railways",
            "Time Table Display": "As per instructions",
            "Public Address System": "Yes",
            "Parking-circulatory area with lights": "As per instructions",
            "Electronic Train indicator board": "As per instructions",
            "Signage": "Yes",
            "Seating arrangement": "100 seats/PF",
            "Latrines": "6",
            "Foot over bridge": "1",
            "Water cooler": "2 on each main PF"
        },
        "Recommended": {
        "Clock": "To be decided by the Zonal Railways",
        "Bathrooms": "1/400 Ndb",
        "Water Coolers": "To be provided if total passengers exceed 1000 per day",
        "IVRS": "24 lines (calls 5000-20000)",
        "Public Address System": "To be decided by the Zonal Railways",
        "Parking-circulatory Area": "To be decided by the Zonal Railways",
        "Electronic Train Indicator Board": "To be decided by the Zonal Railways",
        "Public Phone Booth": "To be decided by the Zonal Railways",
        "Signage": "To be decided by the Zonal Railways",
        "Coach Guidance System": "Available",
        "Insect Catchers": "Not mandatory",
        "Infant Nursing Cubicle": "Not mandatory",
        "Universal Mobile Charging Points": "To be decided by the Zonal Railways",
        "Emergency Lighting": "Backup source from DG set/Solar"
        },
        "Desirable": {
            "Food Courts": "Yes",
            "Prepaid Taxi Service": "Yes",
            "Wheelchair Accessibility": "Yes",
            "Retiring Room": "Yes",
            "Waiting room with bathing facilities": "Yes",
            "Separate waiting for ladies": "Yes",
            "Enquiry System": "Yes",
            "Food Plaza": "Yes",
            "Automatic Vending Machines": "Yes",
            "Coin-operated Ticket Vending Machines": "Yes"
        }
    },
    "NSG-5": {
        "Minimum Essential Amenities": {
            "Drinking water": "8 taps/PF",
            "Waiting hall": "30 sqm",
            "Platform shelter": "50 sqm",
            "Urinals": "4",
            "Lighting": "As per norms",
            "Dustbins": "Yes",
            "Clock": "To be decided by zonal railways",
            "Time Table Display": "As per instructions",
            "Public Address System": "Yes",
            "Parking-circulatory area with lights": "As per instructions",
            "Electronic Train indicator board": "As per instructions",
            "Signage": "Yes",
            "Seating arrangement": "50 seats/PF",
            "Latrines": "4",
            "Foot over bridge": "As per norms"
        },
        "Recommended": {
        "Clock": "To be decided by the Zonal Railways",
        "Bathrooms": "1/400 Ndb",
        "Water Coolers": "To be provided if total passengers exceed 1000 per day",
        "IVRS": "Minimum 6 lines if IVRS is otherwise justified",
        "Public Address System": "To be decided by the Zonal Railways",
        "Parking-circulatory Area": "To be decided by the Zonal Railways",
        "Electronic Train Indicator Board": "To be decided by the Zonal Railways",
        "Public Phone Booth": "To be decided by the Zonal Railways",
        "Signage": "To be decided by the Zonal Railways",
        "Coach Guidance System": "Not mandatory",
        "Insect Catchers": "Not mandatory",
        "Infant Nursing Cubicle": "Not mandatory",
        "Universal Mobile Charging Points": "To be decided by the Zonal Railways",
        "Emergency Lighting": "Backup source from DG set/Solar"
        },
        "Desirable": {
            "Food Courts": "Yes",
            "Prepaid Taxi Service": "Yes",
            "Wheelchair Accessibility": "Yes",
            "Retiring Room": "Yes",
            "Waiting room with bathing facilities": "Yes",
            "Separate waiting for ladies": "Yes",
            "Enquiry System": "Yes",
            "Food Plaza": "Yes",
            "Automatic Vending Machines": "Yes",
            "Coin-operated Ticket Vending Machines": "Yes",
            "Cyber Caf\u00e9": "Yes",
            "Pay & Use Toilets": "Yes",
            "Access Control": "Yes"
        }
    },
    "NSG-6": {
        "Minimum Essential Amenities": {
            "Drinking water": "2 taps/PF",
            "Waiting hall": "15 sqm",
            "Platform shelter": "50 sqm",
            "Urinals": "1",
            "Lighting": "As per norms",
            "Dustbins": "Yes",
            "Clock": "To be decided by zonal railways",
            "Time Table Display": "As per instructions",
            "Public Address System": "Yes",
            "Parking-circulatory area with lights": "As per instructions",
            "Electronic Train indicator board": "As per instructions",
            "Signage": "Yes",
            "Seating arrangement": "50 seats/PF",
            "Latrines": "1",
            "Foot over bridge": "1"
        },
        "Recommended": {
        "Clock": "To be decided by the Zonal Railways",
        "Bathrooms": "1/400 Ndb",
        "Water Coolers": "To be provided if total passengers exceed 1000 per day",
        "IVRS": "Minimum 6 lines if IVRS is otherwise justified",
        "Public Address System": "To be decided by the Zonal Railways",
        "Parking-circulatory Area": "To be decided by the Zonal Railways",
        "Electronic Train Indicator Board": "To be decided by the Zonal Railways",
        "Public Phone Booth": "To be decided by the Zonal Railways",
        "Signage": "To be decided by the Zonal Railways",
        "Coach Guidance System": "Not mandatory",
        "Insect Catchers": "Not mandatory",
        "Infant Nursing Cubicle": "Not mandatory",
        "Universal Mobile Charging Points": "To be decided by the Zonal Railways",
        "Emergency Lighting": "Not mandatory"
        },
        "Desirable": {
            "Food Courts": "Yes",
            "Prepaid Taxi Service": "Yes",
            "Wheelchair Accessibility": "Yes",
            "Retiring Room": "Yes",
            "Waiting room with bathing facilities": "Yes",
            "Separate waiting for ladies": "Yes",
            "Enquiry System": "Yes",
            "Food Plaza": "Yes",
            "Automatic Vending Machines": "Yes",
            "Coin-operated Ticket Vending Machines": "Yes",
            "Signage": "Yes",
            "Bottle crushers, vending machines": "Yes"
        }
    },
    "HG-1": {
        "Minimum Essential Amenities": {
            "Drinking water": "Appropriate drinking water facility",
            "Waiting hall": "10 sqm booking office cum waiting hall",
            "Platform shelter": "Bus type modular shelter",
            "Urinals": "Yes",
            "Lighting": "As per norms",
            "Dustbins": "As per instructions",
            "Clock": "1",
            "Time Table Display": "As per instructions",
            "Public Address System": "Yes",
            "Parking-circulatory area with lights": "As per instructions",
            "Electronic Train indicator board": "As per instructions",
            "Signage": "Yes",
            "Platforms": "High Level",
            "FOB": "1"
        },
        "Recommended": {
      "Drinking Water": "Number of taps = Nmax/25",
      "Waiting Hall/Shed": "1.394 Nds sqm (Excluding C)",
      "Seating Arrangement": "0.4 Nds (No. of seats)",
      "Platform Shelter": "0.28 Nmax, SG/1-3 category stations",
      "Urinals": "Nds/200",
      "Latrines": "Nds/200",
      "Lighting": "As per Board’s letter no. 95/Elec(G)/138/5 dated 19.3.96",
      "Fans": "As per Board’s letter no. 95/Elec(G)/138/5 dated 19.3.96",
      "Time Table Display": "To be decided by the Zonal Railways",
      "Clock": "To be decided by the Zonal Railways",
      "Bathrooms": "1/400 Ndb at other junction & terminal stations only",
      "Insect Catchers": "Available",
      "Infant Nursing Cubicle": "Available",
      "Coach Guidance System": "Available"
        },
        "Desirable": {
            "Food Courts": "Yes",
            "Prepaid Taxi Service": "Yes",
            "Wheelchair Accessibility": "Yes",
            "Retiring Room": "Yes",
            "Waiting room with bathing facilities": "Yes",
            "Separate waiting for ladies": "Yes",
            "Enquiry System": "Yes",
            "Food Plaza": "Yes",
            "Automatic Vending Machines": "Yes",
            "Coin-operated Ticket Vending Machines": "Yes",
            "Book Stalls": "Yes",
            "Water Vending Machines": "Yes",
            "ATMs": "Yes",
            "Pay & Use Toilets": "Yes",
            "Bus type shelter": "Yes"
        }
    },
    "HG-2": {
        "Minimum Essential Amenities": {
            "Drinking water": "Appropriate drinking water facility",
            "Waiting hall": "10 sqm booking office cum waiting hall",
            "Platform shelter": "Shady trees",
            "Urinals": "Yes",
            "Lighting": "As per norms",
            "Dustbins": "As per instructions",
            "Clock": "-",
            "Time Table Display": "As per instructions",
            "Public Address System": "Yes",
            "Parking-circulatory area with lights": "As per instructions",
            "Electronic Train indicator board": "As per instructions",
            "Signage": "Yes",
            "Platforms": "High Level",
            "FOB": "1"
        },
        "Recommended": {
      "Drinking Water": "Number of taps = Nmax/25",
      "Waiting Hall/Shed": "1.394 Nds sqm (Excluding C)",
      "Seating Arrangement": "0.4 Nds (No. of seats)",
      "Platform Shelter": "0.28 Nmax, SG/1-3 category stations",
      "Urinals": "Nds/200",
      "Latrines": "Nds/200",
      "Lighting": "As per Board’s letter no. 95/Elec(G)/138/5 dated 19.3.96",
      "Fans": "As per Board’s letter no. 95/Elec(G)/138/5 dated 19.3.96",
      "Time Table Display": "To be decided by the Zonal Railways",
      "Clock": "To be decided by the Zonal Railways",
      "Bathrooms": "1/400 Ndb at other junction & terminal stations only",
      "Insect Catchers": "Available",
      "Infant Nursing Cubicle": "Not mandatory",
      "Coach Guidance System": "Available"
        },
        "Desirable": {
            "Food Courts": "Yes",
            "Prepaid Taxi Service": "Yes",
            "Wheelchair Accessibility": "Yes",
            "Retiring Room": "Yes",
            "Waiting room with bathing facilities": "Yes",
            "Separate waiting for ladies": "Yes",
            "Enquiry System": "Yes",
            "Food Plaza": "Yes",
            "Automatic Vending Machines": "Yes",
            "Coin-operated Ticket Vending Machines": "Yes"
        }
    },
    "HG-3": {
        "Minimum Essential Amenities": {
            "Drinking water": "Yes",
            "Waiting hall": "-",
            "Platform shelter": "Shady trees",
            "Urinals": "Yes",
            "Lighting": "As per norms",
            "Dustbins": "As per instructions",
            "Clock": "-",
            "Time Table Display": "As per instructions",
            "Public Address System": "Yes",
            "Parking-circulatory area with lights": "As per instructions",
            "Electronic Train indicator board": "As per instructions",
            "Signage": "Yes",
            "Platforms": "High Level",
            "FOB": "1"
        },
        "Recommended": {
      "Drinking Water": "Number of taps = Nmax/25",
      "Waiting Hall/Shed": "1.394 Nds sqm (Excluding C)",
      "Seating Arrangement": "0.4 Nds (No. of seats)",
      "Platform Shelter": "0.28 Nmax, SG/1-3 category stations",
      "Urinals": "Nds/200",
      "Latrines": "Nds/200",
      "Lighting": "As per Board’s letter no. 95/Elec(G)/138/5 dated 19.3.96",
      "Fans": "As per Board’s letter no. 95/Elec(G)/138/5 dated 19.3.96",
      "Time Table Display": "To be decided by the Zonal Railways",
      "Clock": "To be decided by the Zonal Railways",
      "Bathrooms": "1/400 Ndb at other junction & terminal stations only",
      "Insect Catchers": "Not mandatory",
      "Infant Nursing Cubicle": "Not mandatory",
      "Coach Guidance System": "Not mandatory"
        },
        "Desirable": {
            "Food Courts": "Yes",
            "Prepaid Taxi Service": "Yes",
            "Wheelchair Accessibility": "Yes",
            "Retiring Room": "Yes",
            "Waiting room with bathing facilities": "Yes",
            "Separate waiting for ladies": "Yes",
            "Enquiry System": "Yes",
            "Food Plaza": "Yes",
            "Automatic Vending Machines": "Yes",
            "Coin-operated Ticket Vending Machines": "Yes",
            "Bus Shelter": "Yes"
        }
    }
}